services:
  db:
    image: mysql:8.0
    container_name: my-mysql-compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskify_db
    ports:
      - "3307:3306"
    volumes:
      - my-db-volume:/var/lib/mysql

  app:
    build: .
    container_name: taskify-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskify_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  my-db-volume:
